### ISSUE TITLE
Any imba demo using imba@1.3.0 or greater ends with a JavaScript error

### ISSUE THREAD

**Issue by Nock-zz** [somebee/imba#128]
If we take the "Tic-Tac-Toe in imba" example project then when we try to run this we get the following error:
SyntaxError: Unexpected token var

If we now change the dependency to imba@1.2.0 and run then when we run this it works.
So it may be an issue with imba@1.3.0 or greater and my browsers (Brave or Chrome or FireFox) and my os Ubuntu 16.04 but is more likely a compile error in 1.3.0 or greater.

If we take the imba "hello world" example project on a Brave Browser or a Chrome browser when we fork/run the application we get an Syntax "Error: Unexpected token var" error message.

If we change the dependency to imba@1.2.0 then the hello world example still does not work but we get a different error.
Error: Error: Parse error at [228:6]: Unexpected 'SYMBOL' (/app/index.js:1)

This could be because the imba code uses syntax that is applicable to 1.3.0 and not 1.2.0 dunno.

**Comment by somebee** [comment]
Will look into this later today. Thanks for reporting

**Comment by somebee** [comment]
It will work if you update the dependency to Imba 1.4.0. Will investigate why it seems to break on 1.3

**Comment by Nock-zz** [comment]
Hello Sindre,

With imba@1.4.0 I am getting the following error on Chrome, Brave and FF:

TypeError: _1(...).setModel is not a function (/app/index.js:19)

Regards,

Nick

**Comment by somebee** [comment]
Which example are you working with? At some point we renamed tag.model to tag.data, but that was a long time ago.

**Comment by Nock-zz** [comment]
I am working on Scrimba.com Hello World example:

https://scrimba.com/c/cE4nGcg

Regards,

Nick

**Comment by somebee** [comment]
This should be fixed at scrimba now. The example was somehow using old syntax. See my new version https://scrimba.com/c/cE4nGcg.

**Comment by darcyturk** [comment]
> This should be fixed at scrimba now. The example was somehow using old syntax. See my new version https://scrimba.com/c/cE4nGcg.

![image](https://user-images.githubusercontent.com/16271621/51799434-d5c94980-21d5-11e9-8b75-18512deef301.png)

LOL this error is following me on all Scrimba projects, opened the fix you provided. And you may see in my screenshot, after refreshing the preview window, i still get SyntaxError: Unexpected token var
I tried to remove my browsers cache... I am stuck as to what the problem is!!!
I've even tried most versions of Imba with no luck, I've brought this up on Scrimba but it doesn't seem to be getting any attention. This bug occurs despite in some of my playgrounds i am not even using a single var.. I'm tempted to go back to react because, cause a working code sandbox is incredibly dire for me to be able to quickly jump demos up... and this is beginning to take too much time to learn Imba through, any direction would be awesome... I hope there's a simple explanation for what I'm encountering. Thank you.
